# Generated by Django 3.0.8 on 2020-08-02 01:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diseaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseField', multiselectfield.db.fields.MultiSelectField(choices=[('Asthma', 'Asthma'), ('Melanoma', 'Melanoma'), ('Photoaging', 'Photoaging'), ('Basal Cell Carcinoma', 'Basal Cell Carcinoma'), ('Dysautonomia', 'Dysautonomia'), ('Lung Cancer', 'Lung Cancer'), ('Pneumonia', 'Pneumonia'), ('Chronic Bronchitis', 'Chronic Bronchitis'), ('Cystic Fibrosis', 'Cystic Fibrosis'), ('Diabetes', 'Diabetes'), ('Arthritis', 'Arthritis'), ('Epilepsy', 'Epilepsy'), ('Migraines', 'Migraines'), ('Seasonal Allergic Rhinitis', 'Seasonal Allergic Rhinitis'), ('Pollen Allergy', 'Pollen Allergy'), ('Dust Allergy', 'Dust Allergy'), ('Albinism', 'Albinism'), ('Photodermatitis', 'Photodermatitis'), ('Hyperhidrosis', 'Hyperhidrosis')], max_length=249)),
            ],
        ),
    ]
